#!/usr/bin/php
<?php

$variables = array();

$fp = fopen("php://stdin", "r");
while ( $line = fgets($fp, 1024) )
{
    $input .=$line;
    preg_match('~private \s*\$([A-Za-z0-9-_]+)\s*.*;\s*~i', $line ,$fertig);
    if ($fertig[1]=="")
    {
	preg_match('~public \s*\$([A-Za-z0-9-_]+)\s*.*;\s*~i', $line, $fertig);
	if ($fertig[1]=="")
	{
		preg_match('~protected \s*\$([A-Za-z0-9-_]+)\s*.*;\s*~i', $line, $fertig);
    	} 
    }    if ($fertig[1]!="")
    {
        $variables[] = $fertig[1];
    }
}
fclose($fp);


foreach ($variables as $variable)
{
    echo "public function set_".$variable."(\$value){
    \$this->".$variable." = \$value;
}
";
}

?>