#!/usr/bin/php
<?php

$variables = array();

$fp = fopen("php://stdin", "r");
while ( $line = fgets($fp, 1024) )
{
    $input .=$line;
    preg_match('~protected \s*\$([A-Za-z0-9-_]+)\s*.*;\s*~i', $line, $fertig);
    if ($fertig[1]!="")
    {
        $variables[] = $fertig[1];
    }
}
fclose($fp);


foreach ($variables as $variable)
{
    echo <<<eof
public function get_{$variable} () {
	return \$this->{$variable};
}

eof;
}

?>